### ISSUE TITLE
npm run dev页面打开空白

### ISSUE THREAD

**Issue by kfcvime50** [gengbingbing/vue-tools#1]
npm run dev页面打开空白，命名视图哪里有问题吗，找不到啊

**Comment by gengbingbing** [comment]
需要删除package-lock.json，重新npm install一下，下面是测试地址
http://120.27.249.181/vueTool/index.html#/

**Comment by kfcvime50** [comment]
提示还有这个Named Route 'home' has a default child route. When navigating to this named route (:to="{name: 'home'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.

**Comment by gengbingbing** [comment]
修改下路由，就可以了，已修改
